### PR TITLE
Faster blog post

### PR DESCRIPTION
**Pull request by MikeBallan**
image

### CODE REVIEW

**Comment by shahrukhomar** [comment]
:(
boo

**Comment by MikeBallan** [comment]
Soz Mr @shahrukhomar :(

**Comment by catchamonkey** [comment]
Does the new styling affect the other existing post?
Do you want to add an H2 to it?

**Comment by MikeBallan** [comment]
@catchamonkey Was going to do another PR for the other post but happy to include it in this one!

**Comment by MikeBallan** [comment]
image

**Pull request merged**
